### ISSUE TITLE
support@kashhcoin.net

### ISSUE THREAD

**Issue by 1975krishna** [cashhcointech/kashhcoin#1]
81582  this Transaction id is not credit my kashh wallet   amount  5320

Sl.	Transaction ID	Date	Remarks	Amount
1.	81582	13Jan17 11:55:00	a8384622d7d832894626993a360c0605700ecb0bfa6c93be9535cebdbd43e23c	5320

**Comment by arjunmsh** [comment]
Hello @1975krishna ,
This probably was a delayed confirmation!
http://107.180.71.154:3001/tx/a8384622d7d832894626993a360c0605700ecb0bfa6c93be9535cebdbd43e23c

We recommend you to explore the block and wait for 3-14 confirmations! Thanks for you co-operation!
